In [5]:
import torch
import numpy as np

In [7]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
type(x_data)

torch.Tensor

In [9]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(type(x_np))

<class 'torch.Tensor'>


In [10]:
x_ones = torch.ones_like(x_data) # x_data의 속성을 유지합니다.
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # x_data의 속성을 덮어씁니다.
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.2396, 0.2411],
        [0.7153, 0.8421]]) 



In [11]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.5620, 0.3683, 0.6719],
        [0.5232, 0.2233, 0.4207]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [12]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [13]:
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [14]:
tensor

tensor([[0.0661, 0.7577, 0.5071, 0.5756],
        [0.1809, 0.6467, 0.0870, 0.7451],
        [0.5372, 0.2137, 0.0360, 0.2780]], device='cuda:0')

In [15]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[0.0661, 0.7577, 0.5071, 0.5756, 0.0661, 0.7577, 0.5071, 0.5756, 0.0661,
         0.7577, 0.5071, 0.5756],
        [0.1809, 0.6467, 0.0870, 0.7451, 0.1809, 0.6467, 0.0870, 0.7451, 0.1809,
         0.6467, 0.0870, 0.7451],
        [0.5372, 0.2137, 0.0360, 0.2780, 0.5372, 0.2137, 0.0360, 0.2780, 0.5372,
         0.2137, 0.0360, 0.2780]], device='cuda:0')


In [16]:
# 두 텐서 간의 행렬 곱(matrix multiplication)을 계산합니다. y1, y2, y3은 모두 같은 값을 갖습니다.
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)


# 요소별 곱(element-wise product)을 계산합니다. z1, z2, z3는 모두 같은 값을 갖습니다.
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[0.0044, 0.5741, 0.2571, 0.3314],
        [0.0327, 0.4182, 0.0076, 0.5552],
        [0.2886, 0.0457, 0.0013, 0.0773]], device='cuda:0')

In [18]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))
print(agg)

4.631080627441406 <class 'float'>
tensor(4.6311, device='cuda:0')
