 + tensorflow 특징
   + 계산과정을 graph로 표현
   + 그래프는 session에 올려서 실행
   + 실행 결과는 list, numpy로 변환

tf 동작 과정
 1. 데이터 플로우 그래프 빌드
 2. 데이터 입력하고 그래프 실행(run)
 3. 그래프 내부 변수들을 update하고 출력값 리턴

In [1]:
import tensorflow as tf

c:\users\admin\anaconda3\envs\gpu\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
c:\users\admin\anaconda3\envs\gpu\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
c:\users\admin\anaconda3\envs\gpu\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
c:\users\admin\anaconda3\envs\gpu\lib\site-packages\tensorflow\python\framework

In [4]:
#그래프 빌딩
x = tf.constant(1)
y = tf.constant(2)
z = tf.constant(3)

a = x*y+z


In [5]:
sess = tf.Session()
b = sess.run(a)
print(b)

5


텐서 생성

In [7]:
a = tf.constant([[1,2],[3,4],[5,6]])
print(a.dtype)
print(a.shape)
print(sess.run(tf.rank(a))) #차원 계산

<dtype: 'int32'>
(3, 2)
2


In [12]:
a = tf.constant([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
b = tf.reshape(a,[3,4])
c = tf.transpose(b)
print(sess.run(b))
print(sess.run(c))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [16]:
a = tf.constant([1,2,3,4,5])
b = tf.constant([-1,-1,-1,-1,-1])
c = a*b
print(f"c type = {type(c)}")
print(f"{sess.run(c)}  type = {type(sess.run(c))}")

c type = <class 'tensorflow.python.framework.ops.Tensor'>
[-1 -2 -3 -4 -5]  type = <class 'numpy.ndarray'>


In [18]:
a = tf.constant([1,2,3,4,5])
b = tf.constant([1,4,6,4,9])
c = tf.equal(a,b)
print(sess.run(c))

[ True False False  True False]


### 텐서 사칙연산!