학습은 학습 데이터를 가장 잘 설명할 수 있는 직선을 찾는 것  
오차 최소화  
선형회귀 -> 기울기 w와 y절편 b 구함  
로지스틱회귀 -> 2개의 클래스로 잘 분류하는 sigmoid 함수 파라미터 추정  
신경망 -> 가중치 값 찾기  
CNN -> 시각적인 학습  

NUMPY -> Python for문보다 행렬곱 6배정도 빠름..

# 1.numpy 기초 

### numpy array 생성

In [24]:
import numpy as np
import numpy.linalg as lin #선형대수 모듈
import time

In [3]:
V = np.array([2,3,4])
M = np.array([[1,2],[3,4],[5,6]])
M = np.array([[1,2,3]])
M = np.array([[1],[2],[3]])
M = np.array([[1,2,3],[4,5,6]]).reshape(3,2)
M = np.array([[1,2,3],[4,5,6]]).T

In [19]:
a = np.array([1,3,5,7,9])
b = np.array([3,5,6,7,9])
c = a + b
c

array([ 4,  8, 11, 14, 18])

In [20]:
x = np.array([[1,2],[4,5],[6,7]])
y = np.array([[1,2],[4,5]])
print(np.matmul(x,y))

[[ 9 12]
 [24 33]
 [34 47]]


In [25]:
a = np.array(2.0)
print(a)

2.0


In [26]:
print(type(a))

<class 'numpy.ndarray'>


In [27]:
print(a.shape)
if a.shape == (): print("차원 0")

()
차원 0


In [29]:
b = np.array([2.0])
print(b)
print(f"shape {b.shape}")
print(f"length {b.shape[0]}")

[2.]
shape (1,)
length 1


In [33]:
c = np.array([2,3,4])
print(c)
print(f"shape {c.shape}")
print(f"length {c.shape[0]}")

[2 3 4]
shape (3,)
length 3


In [34]:
m = np.array([[1,2],[3,4],[5,6]])
print(m)
print(f"shape {m.shape}")
print(f"행 : {m.shape[0]} 열 : {m.shape[1]}")

[[1 2]
 [3 4]
 [5 6]]
shape (3, 2)
행 : 3 열 : 2


In [35]:
m = np.array([[1,2,3]])
print(m)
print(m.shape)

[[1 2 3]]
(1, 3)


In [36]:
m = np.array([[1],[2],[3]])
print(m)
print(m.shape)

[[1]
 [2]
 [3]]
(3, 1)


In [37]:
a = [1, 2.0]
b = np.array([1, 2, 3])
c = np.array([1, 2, 3.0])

print(type(a[0]))
print(type(a[1]))
print(b.dtype)
print(c.dtype)
print(type(c[0]))
print(type(c[2]))

<class 'int'>
<class 'float'>
int32
float64
<class 'numpy.float64'>
<class 'numpy.float64'>


In [38]:
a = [[1, 2 ], [3,4,5]]
print(a)
b = np.array([[1, 2 ], [3,4,5]])
print(b)

[[1, 2], [3, 4, 5]]
[list([1, 2]) list([3, 4, 5])]


c:\users\admin\anaconda3\envs\gpu\lib\site-packages\ipykernel_launcher.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  This is separate from the ipykernel package so we can avoid doing imports until


numpy는 격자 array만 지원  
=> 각각의 리스트

### numpy 원소 접근

In [39]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]] )
print(a) 
print("a[0,0]==>", a[0,0])
print("a[0]==>", a[0])
print("a[:,1] ==> " , a[:,1]) 
print("a[1, 1:3] ==> ", a[1, 1:3]) 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
a[0,0]==> 1
a[0]==> [1 2 3]
a[:,1] ==>  [2 5 8]
a[1, 1:3] ==>  [5 6]


In [40]:
i = [0, 2]
b = a[i, :]
print(b)

[[1 2 3]
 [7 8 9]]


In [41]:
c = np.array([1,2,3,4,5,6,7,8,9])
print(c[0::2])

[1 3 5 7 9]


In [42]:
print(a[1:-1]) 

[[4 5 6]]


In [43]:
print(a[1:]) 

[[4 5 6]
 [7 8 9]]


In [44]:
print(a)
a[1, 2] = 7 
a[:, 0] = [0, 9, 1] 
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0 2 3]
 [9 5 7]
 [1 8 9]]


In [45]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12,], [13,14,15,16]] )
print(a)

a[1:-1,1:-1] = 0
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4]
 [ 5  0  0  8]
 [ 9  0  0 12]
 [13 14 15 16]]


### numpy shape

In [46]:
a = np.array([[1,2,3], [4,5,6]])
b = np.array([[1,2,3], [4,5,6]]).T
c = np.array([[1,2,3], [4,5,6]]).transpose()
print( a.shape, b.shape, c.shape)

(2, 3) (3, 2) (3, 2)


In [47]:
a = np.array([[1,2,3,4]])        
b = np.array([[1,2,3,4]]).T      
print(a)
print(b)
print(a.shape)
print(b.shape)

[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]
(1, 4)
(4, 1)


1차원 transpose

In [48]:
a = np.array([1,2,3,4])              
b = np.array([1,2,3,4]).T     
print(a.shape, b.shape)

(4,) (4,)


In [49]:
a = np.array([[1,2], [3,4], [5,6], [7,8], [9,10], [11,12]])
b = a.reshape(3,4) 
print(a.shape)
print(a)
print(b.shape)
print(b)

(6, 2)
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
(3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [50]:
a = np.array([1,2,3,4,5,6])
b = a.reshape(2,3) 
print(a)
print(a.shape)
print(b)
print(b.shape)

[1 2 3 4 5 6]
(6,)
[[1 2 3]
 [4 5 6]]
(2, 3)


In [51]:
a = np.array([[1], [2], [3], [4]]) 
b = np.array([[1,2,3,4]]).T
c = np.array([1,2,3,4]).reshape(4,1) 
d = np.array([1,2,3,4]).T
print(a)
print(b)
print(c)
print(d)

[[1]
 [2]
 [3]
 [4]]
[[1]
 [2]
 [3]
 [4]]
[[1]
 [2]
 [3]
 [4]]
[1 2 3 4]


### numpy 저장 & 로딩

In [53]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]] )
np.save("a.npy", a)
b = np.load("a.npy")   
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [55]:
data = np.loadtxt("iris.csv", delimiter=",", dtype=np.float32)
print(data[0:5,:])

[[5.1 3.5 1.4 0.2 1. ]
 [4.9 3.  1.4 0.2 1. ]
 [4.7 3.2 1.3 0.2 1. ]
 [4.6 3.1 1.5 0.2 1. ]
 [5.  3.6 1.4 0.2 1. ]]


#  2.기본 연산

In [56]:
a = np.array([1,3,5,7,9]) 
b = np.array([3,5,6,7,9])
c = a + b
print(c)
print(type(c))
print(c.dtype)

[ 4  8 11 14 18]
<class 'numpy.ndarray'>
int32


In [57]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 2, 3, 4, 5])
print( np.sum(a*b))

55


두 점 거리 계산

In [58]:
p = np.array([2, 2])
q = np.array([3, 7])
(np.sum(  (p-q) ** 2) ) ** (0.5)

5.0990195135927845

In [59]:
a = np.array([1, 2, 3, 3, 2, 5]).reshape(2,3) 
b = np.array([[-1,3,5],[1,4,2]])
print(a)
print(b)
print(a+b )

[[1 2 3]
 [3 2 5]]
[[-1  3  5]
 [ 1  4  2]]
[[0 5 8]
 [4 6 7]]


In [60]:
a = np.array([1, 2, 3, 3, 2, 5]).reshape(2,3) 
b = np.array([[-1,-1, -1],[0, 0, 0]])
print(a)
print(b)
print(a*b )

[[1 2 3]
 [3 2 5]]
[[-1 -1 -1]
 [ 0  0  0]]
[[-1 -2 -3]
 [ 0  0  0]]


In [61]:
a = np.array([[1,2], [3,4], [5,6]])
b = a ** 2
c = a * a
print(b)
print(c)

[[ 1  4]
 [ 9 16]
 [25 36]]
[[ 1  4]
 [ 9 16]
 [25 36]]


In [63]:
x = np.array([[1,2],[4,5], [6,7]])
y = np.array([[1,2],[4,5]])
print(x)
print(y)
print(np.matmul(x, y))

[[1 2]
 [4 5]
 [6 7]]
[[1 2]
 [4 5]]
[[ 9 12]
 [24 33]
 [34 47]]


In [64]:
x = np.array([[1,2,3],[4,5,6]])    # 2 x 3

print(np.matmul(x, x.T))
print(np.matmul(x, np.transpose(x) ))

[[14 32]
 [32 77]]
[[14 32]
 [32 77]]


### python - numpy 속도 비교

In [66]:
# numpy
a = np.random.normal(0, 0.1, [500,500])
b = np.random.normal(0, 0.1, [500,500])

start_time = time.time() 
c = np.matmul(a, b)
print(time.time() - start_time)

0.0029926300048828125


In [67]:
#python
def matmul_py(A, B):
    m = len(A)
    n = len(A[0])
    p = len(B[0])
    C = [[0]*p for i in range(m)]      

    
    for i in range(0,m):
        for j in range(0,p):
            for k in range(0,n):
                C[i][j] += A[i][k]*B[k][j] 
    return C


A = a.tolist()
B = b.tolist()
start_time = time.time() 
matmul_py(A,B)
print(time.time() - start_time)


19.682432889938354


### 역행렬

정방 행렬만 가능

In [68]:
a = np.array([[2,2,0],[-2,1,1],[3,0,1]])
inv = lin.inv(a)
print(inv.shape)
print(inv.dtype)
print(inv)

(3, 3)
float64
[[ 0.08333333 -0.16666667  0.16666667]
 [ 0.41666667  0.16666667 -0.16666667]
 [-0.25        0.5         0.5       ]]


일반 행렬에 역행렬 구하기

In [69]:
A = np.array([[1,2], [2,4], [3,6.4]]) 
pinv = np.matmul(np.linalg.inv(np.matmul(A.T, A)), A.T)  
print(A)
print(pinv)

[[1.  2. ]
 [2.  4. ]
 [3.  6.4]]
[[ 3.2  6.4 -5. ]
 [-1.5 -3.   2.5]]


In [70]:
def pinv(A) :
    return np.matmul(np.linalg.inv(np.matmul(A.T, A)), A.T)

A = np.array([[1,2], [2,4], [3,6.4]]) 
print(pinv(A))

[[ 3.2  6.4 -5. ]
 [-1.5 -3.   2.5]]


###  브로드캐스팅

In [71]:
a = np.array([1, 2, 3, 4, 5, 6])
b = a + 4
print(a)
print(b)

[1 2 3 4 5 6]
[ 5  6  7  8  9 10]


In [72]:
a = np.array([1, 2, 3, 4, 5, 6])
b = a * 2
print(a)
print(b)

[1 2 3 4 5 6]
[ 2  4  6  8 10 12]


In [73]:
a = np.array([1, 2, 3, 4, 5, 6])
b = a * 2 + 3
print(a)
print(b)

[1 2 3 4 5 6]
[ 5  7  9 11 13 15]


In [75]:
#(화씨온도 - 32) ÷ 1.8 = 섭씨온도
a = np.array([78, 77,76,75])
b= (a - 32)  / 1.8
print(a)
print(b)

[78 77 76 75]
[25.55555556 25.         24.44444444 23.88888889]


In [76]:
# (섭씨온도 × 1.8) + 32 = 화씨온도
a = np.array([26,25,24,23])
b = a * 1.8 + 32
print(a)
print(b)

[26 25 24 23]
[78.8 77.  75.2 73.4]


In [77]:
a = np.arange(31)
b = a * 1.8 + 32
print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]
[32.  33.8 35.6 37.4 39.2 41.  42.8 44.6 46.4 48.2 50.  51.8 53.6 55.4
 57.2 59.  60.8 62.6 64.4 66.2 68.  69.8 71.6 73.4 75.2 77.  78.8 80.6
 82.4 84.2 86. ]


In [78]:
#정수 반올림
a = np.array([121.5732, 458.4221])
b =  ((a +5)/ 10).astype(int) * 10
print(a)
print(b)

[121.5732 458.4221]
[120 460]


In [79]:
#실수 반올림
a = np.array([31.5732, 8.4221])
b =  ((a +0.05)* 10).astype(int) / 10
print(a)
print(b)

[31.5732  8.4221]
[31.6  8.4]


In [80]:
x = np.array([1,2,3,4,5])
w = 4.5
b = 7.2
print(w*x + b)

[11.7 16.2 20.7 25.2 29.7]


In [81]:
x = np.arange(-3, 3, 1) 
print(x)
print(2 * x + 0.1)

[-3 -2 -1  0  1  2]
[-5.9 -3.9 -1.9  0.1  2.1  4.1]


In [82]:
a = np.array([1, 2, 3, 4, 5, 6])
a2 = np.array([4 for i in range(6)])
print(a)
print(a2)
print(a + a2)

[1 2 3 4 5 6]
[4 4 4 4 4 4]
[ 5  6  7  8  9 10]


In [83]:
a = np.array([1, 2, 3, 4, 5, 6]).reshape(2,3) 
b = a + 4
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[ 5  6  7]
 [ 8  9 10]]


In [84]:
a = np.array([1, 2, 3, 4, 5, 6]).reshape(2,3) 
b = a * -1
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[-1 -2 -3]
 [-4 -5 -6]]


In [85]:
a = np.array([ [1,1,1], [1,1,1], [1,1,1] ])         
b = np.array([0,1,2])  
print( a + b) 

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [86]:
a = np.array([ [1,2,3], [4,5,6] ])         
b = np.array([1,2,3])  
print( a + b) 

[[2 4 6]
 [5 7 9]]


In [87]:
x = np.array([ [1,2], [3 ,4], [5,6], [7,8] ]) 
w = np.array([ [0.1,0.2, 0.3], [0.2,0.3, 1]])
b = np.array([1,2,3])
print(np.matmul(x, w) + b)

[[ 1.5  2.8  5.3]
 [ 2.1  3.8  7.9]
 [ 2.7  4.8 10.5]
 [ 3.3  5.8 13.1]]


브로드캐스팅 정규화

In [88]:
a = np.array([ [0.1, 2, 34], [0.9, 7, 12], [0.2, 1, 6], [0.5, 1.5, 27] ])
n = a / np.max(a, axis=0)
print(a)
print(n)

[[ 0.1  2.  34. ]
 [ 0.9  7.  12. ]
 [ 0.2  1.   6. ]
 [ 0.5  1.5 27. ]]
[[0.11111111 0.28571429 1.        ]
 [1.         1.         0.35294118]
 [0.22222222 0.14285714 0.17647059]
 [0.55555556 0.21428571 0.79411765]]


# 3. 수학 점수 예측

1) 13,15,20 시간 공부하면 SAT는 몇점인지 예측

2) SAT 840점을 얻기 위해 몇 시간 공부야 하는가?

3) 최적 w,b로 부터 발생하는 학습 오차는 얼마인가?

4) 최적의 가중치 w, b 는 얼마인가?

5) 이전 모델보다 좋은가?

In [89]:
w = 20.3
b = 351.2
x = [13, 15, 20]
y = np.array(x) * w + b
print(y)

[615.1 655.7 757.2]


In [90]:
y = 840
x = (y  - b) / w
print(y)
print(x)

840
24.078817733990146


학습 오차 계산

In [91]:
w = 20.3
b = 351.2

x = np.array([4,9,10,14,4,7,12,22,1,3,8,11,5,6,10,11,16,13,13,10])
y = np.array([390,580,650,730,410,530,600,790,350,400,590,640,450,520,690,690,770,700,730,640])

error = (y - (x*w+b))**2
result = np.sqrt(np.mean(error) )

print(result)

72.56996968443626


In [92]:
x = np.array([[4,9,10,14,4,7,12,22,1,3,8,11,5,6,10,11,16,13,13,10]]).T
y = np.array([[390,580,650,730,410,530,600,790,350,400,590,640,450,520,690,690,770,700,730,640]]).T
print(x.shape)
print(y.shape)

(20, 1)
(20, 1)


In [93]:
A = np.append(x, np.ones((x.shape[0], 1)), axis = 1)
print(A)
print(A.shape)

[[ 4.  1.]
 [ 9.  1.]
 [10.  1.]
 [14.  1.]
 [ 4.  1.]
 [ 7.  1.]
 [12.  1.]
 [22.  1.]
 [ 1.  1.]
 [ 3.  1.]
 [ 8.  1.]
 [11.  1.]
 [ 5.  1.]
 [ 6.  1.]
 [10.  1.]
 [11.  1.]
 [16.  1.]
 [13.  1.]
 [13.  1.]
 [10.  1.]]
(20, 2)


In [94]:
def pinv(A) :
    return np.matmul(np.linalg.inv(np.matmul(A.T, A)), A.T)

W = np.matmul(  pinv(A), y)
w,b = W
print(w, b)

[25.32646778] [353.1648795]


In [95]:
error2 = (y - (x*w+b))**2
result2 = np.sqrt(np.mean(error2) )

print(result)
print(result2)

72.56996968443626
47.16649000039569


###  이자율에 따른 주가 / 실업률에 따른 주가 

In [96]:
Interest_Rate =  np.array([[2.75,2.5,2.5,2.5,2.5,2.5,2.5,2.25,2.25,2.25,2,2,2,1.75,1.75,1.75,1.75,1.75,1.75,1.75,1.75,1.75,1.75,1.75]]).T
Unemployment_Rate = np.array([[5.3,5.3,5.3,5.3,5.4,5.6,5.5,5.5,5.5,5.6,5.7,5.9,6,5.9,5.8,6.1,6.2,6.1,6.1,6.1,5.9,6.2,6.2,6.1]]).T
Stock_Index_Price =  [1464,1394,1357,1293,1256,1254,1234,1195,1159,1167,1130,1075,1047,965,943,958,971,949,884,866,876,822,704,719]

A = np.append(Interest_Rate, Unemployment_Rate, axis = 1)
A = np.append(A, np.ones((Interest_Rate.size , 1)), axis = 1)
print(A.shape)

W = np.matmul(pinv(A), Stock_Index_Price)
print(W)

(24, 3)
[ 345.54008701 -250.14657137 1798.40397762]


In [97]:
x_data = np.array([[5.1, 6.2, 1], [5.1,6.1, 1], [5.1, 6.2 ,1], [5.2, 6.2, 1] ])
result = np.matmul(x_data, W)
print(result)

[2009.74967889 2034.76433603 2009.74967889 2044.30368759]


In [98]:
print( result[1]-result[0])
print( result[3]-result[2])

25.01465713690959
34.55400870107587
