 + tensorflow 특징
   + 계산과정을 graph로 표현
   + 그래프는 session에 올려서 실행
   + 실행 결과는 list, numpy로 변환

tf 동작 과정
 1. 데이터 플로우 그래프 빌드
 2. 데이터 입력하고 그래프 실행(run)
 3. 그래프 내부 변수들을 update하고 출력값 리턴

In [1]:
import tensorflow as tf

c:\users\admin\anaconda3\envs\gpu\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
c:\users\admin\anaconda3\envs\gpu\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
c:\users\admin\anaconda3\envs\gpu\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
c:\users\admin\anaconda3\envs\gpu\lib\site-packages\tensorflow\python\framework

In [4]:
#그래프 빌딩
x = tf.constant(1)
y = tf.constant(2)
z = tf.constant(3)

a = x*y+z


In [5]:
sess = tf.Session()
b = sess.run(a)
print(b)

5


텐서 생성

In [7]:
a = tf.constant([[1,2],[3,4],[5,6]])
print(a.dtype)
print(a.shape)
print(sess.run(tf.rank(a))) #차원 계산

<dtype: 'int32'>
(3, 2)
2


In [12]:
a = tf.constant([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
b = tf.reshape(a,[3,4])
c = tf.transpose(b)
print(sess.run(b))
print(sess.run(c))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [16]:
a = tf.constant([1,2,3,4,5])
b = tf.constant([-1,-1,-1,-1,-1])
c = a*b
print(f"c type = {type(c)}")
print(f"{sess.run(c)}  type = {type(sess.run(c))}")

c type = <class 'tensorflow.python.framework.ops.Tensor'>
[-1 -2 -3 -4 -5]  type = <class 'numpy.ndarray'>


In [18]:
a = tf.constant([1,2,3,4,5])
b = tf.constant([1,4,6,4,9])
c = tf.equal(a,b)
print(sess.run(c))

[ True False False  True False]


### 텐서 자료형!

tf.constant = 상수 저장 고정 크기 메모리  
tf.placeholder = 학습 데이터 저장 가변크기 메모리  
tf.Variable = 학습 파라미터 저장 고정크기 메모리

In [3]:
#tf.constant(value, dtype, shape)
a = tf.constant([5])
b = tf.constant([10.0,20,30])
c = tf.constant([10,20,30], dtype=tf.float32)

In [8]:
sess = tf.Session()

In [11]:
x = tf.placeholder(dtype=tf.float32)
input_data = [1,2,3,4,5]
sess.run(x, feed_dict = {x:input_data})

array([1., 2., 3., 4., 5.], dtype=float32)

In [12]:
#tf.Variable(value, dtype, shape)
w = tf.Variable(input_data, dtype=tf.float32)
init = tf.global_variables_initializer()
sess.run(init)

3개 데이터타입 예제

In [16]:
input_data = [1,2,3,4,5]
x = tf.placeholder(dtype=tf.float32)
w = tf.Variable([2.0])
b= tf.constant([1.4])
y = w*x + b

init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

out1 = sess.run(y, feed_dict={x:[1,2,3]})
out2 = sess.run(y, feed_dict={x:[-1.0, -2.0]})

# 예제 

## * 상수타입 

In [17]:
a = tf.constant(2.0)
print(a)
print(sess.run(a))

Tensor("Const_8:0", shape=(), dtype=float32)
2.0


In [18]:
print(type(a))
print(a.shape)

<class 'tensorflow.python.framework.ops.Tensor'>
()


In [19]:
b = tf.constant([2,0])
print(sess.run(b))

[2 0]


In [20]:
a= tf.constant(4)
b= tf.constant([4])
print(a)
print(b)

Tensor("Const_10:0", shape=(), dtype=int32)
Tensor("Const_11:0", shape=(1,), dtype=int32)


In [21]:
a_ = sess.run(a)
b_ = sess.run(b)
print(a_, type(a_))
print(b_, type(b_))

4 <class 'numpy.int32'>
[4] <class 'numpy.ndarray'>


In [22]:
print(b.shape)
print("length : ",b.shape[0])

(1,)
length :  1


In [23]:
c = tf.constant([2,3,4])
print(c)
print(c.shape)
print("length : ",c.shape[0])

Tensor("Const_12:0", shape=(3,), dtype=int32)
(3,)
length :  3


In [24]:
m = tf.constant([[1,2],[3,4],[5,6]])
print(m)
print(m.shape)
print(f"행 : {m.shape[0]}")
print(f"열 : {m.shape[1]}")

Tensor("Const_13:0", shape=(3, 2), dtype=int32)
(3, 2)
행 : 3
열 : 2


In [26]:
m = tf.constant([[1,2,3]])
print(m)
print(m.shape)

Tensor("Const_15:0", shape=(1, 3), dtype=int32)
(1, 3)


#### shape 행  : [0]  / 열 : [1]

In [27]:
m = tf.constant([[1],[2],[3]])
print(m)
print(m.shape)

Tensor("Const_16:0", shape=(3, 1), dtype=int32)
(3, 1)


In [28]:
import numpy as np

In [31]:
a = [1, 2.0]
b = np.array([1,2,3.0])
c = tf.constant([1,2,3.0])
print('1',type(a[0]))
print('2',type(a[1]))
print('3',b.dtype)
print('4',type(b[0]))
print('5',type(b[1]))

print('6',c)
c2 = sess.run(c)
print('7',type(c2[0]))


1 <class 'int'>
2 <class 'float'>
3 float64
4 <class 'numpy.float64'>
5 <class 'numpy.float64'>
6 Tensor("Const_18:0", shape=(3,), dtype=float32)
7 <class 'numpy.float32'>


In [33]:
# 텐서는 dense tensor만 ㄴㄴ! 격자 행렬만 취급
a = [[1,2],[3,4,5]]
print(a)

[[1, 2], [3, 4, 5]]


In [35]:
a = tf.constant([1,2,3,4,5,6])
print(a.shape)
b = tf.constant([[1,2,3,4,5,6]])
print(b.shape.as_list())
c= tf.constant([[1],[2],[3],[4],[5],[6]])
print(c.shape.as_list())
d = tf.constant([[1,2],[3,4],[5,6]])
print(d.shape.as_list())

(6,)
[1, 6]
[6, 1]
[3, 2]


In [36]:
a = tf.constant([1,2,3,4,5,6], shape = (2,3))
print(sess.run(a))

[[1 2 3]
 [4 5 6]]


In [37]:
print(sess.run(tf.constant(0, shape=[4,2])))

[[0 0]
 [0 0]
 [0 0]
 [0 0]]


In [38]:
print(sess.run(tf.constant([0,1,2], shape=[4,2])))

[[0 1]
 [2 2]
 [2 2]
 [2 2]]


In [39]:
a = tf.constant([[1,2,3],[4,5,6]])
b = tf.transpose(a)
print(a.shape, b.shape)

(2, 3) (3, 2)


In [41]:
a = tf.constant([1,2,3,4])
b = tf.transpose(a)
print(a.shape, b.shape)

(4,) (4,)


In [42]:
a = tf.constant([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
b = tf.reshape(a,[3,4])
print(a.shape)
print(sess.run(a))
print(b.shape)
print(sess.run(b))

(6, 2)
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
(3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [43]:
a = tf.constant([1,2,3,4,5,6])
b = tf.reshape(a,[2,3])
print(a.shape)
print(sess.run(a))
print(b.shape)
print(sess.run(b))

(6,)
[1 2 3 4 5 6]
(2, 3)
[[1 2 3]
 [4 5 6]]


In [44]:
a = tf.constant([[1],[2],[3],[4]])
b= tf.transpose([[1,2,3,4]])
c = tf.reshape([1,2,3,4],[4,1])
d = tf.transpose([1,2,3,4])
print(sess.run(a))
print(sess.run(b))
print(sess.run(c))
print(sess.run(d))



[[1]
 [2]
 [3]
 [4]]
[[1]
 [2]
 [3]
 [4]]
[[1]
 [2]
 [3]
 [4]]
[1 2 3 4]


In [48]:
a = tf.constant([6,7,8],shape = (3,1))
b= tf.constant([[1,2,3]],shape=(3,1))
c = tf.constant([[1,2,3,4]], shape=(2,2))
d = tf.constant([1,2,3,4,5,6], shape=(2,3))
print(sess.run(a))
print(sess.run(b))
print(sess.run(c))
print(sess.run(d))

[[6]
 [7]
 [8]]
[[1]
 [2]
 [3]]
[[1 2]
 [3 4]]
[[1 2 3]
 [4 5 6]]


### 텐서 기본 연산

In [49]:
a = tf.constant([1.0, 2.0, 3.0])
b = tf.constant([1.0, 2.0, 3.0])
c = a + b
d = a - b 
e = a * b 
f = a / b
print(sess.run(c))
print(sess.run(d))
print(sess.run(e))
print(sess.run(f))

[2. 4. 6.]
[0. 0. 0.]
[1. 4. 9.]
[1. 1. 1.]


In [50]:
a = tf.constant([1,2,3,4,5,6])
b = tf.constant([2, 0, 2, 0, 2,0])
c = a * b
print(sess.run(c))

[ 2  0  6  0 10  0]


In [51]:
a = tf.constant([1,2,3]) 
b = tf.constant([4,5,6]) 
c = a * b
print(a)
print(b)
print(c)

Tensor("Const_43:0", shape=(3,), dtype=int32)
Tensor("Const_44:0", shape=(3,), dtype=int32)
Tensor("mul_4:0", shape=(3,), dtype=int32)


In [52]:
print(a.op)

name: "Const_43"
op: "Const"
attr {
  key: "dtype"
  value {
    type: DT_INT32
  }
}
attr {
  key: "value"
  value {
    tensor {
      dtype: DT_INT32
      tensor_shape {
        dim {
          size: 3
        }
      }
      tensor_content: "\001\000\000\000\002\000\000\000\003\000\000\000"
    }
  }
}



In [54]:
print(c.op)

name: "mul_4"
op: "Mul"
input: "Const_43"
input: "Const_44"
attr {
  key: "T"
  value {
    type: DT_INT32
  }
}



In [55]:
a = tf.constant([1,2,3,4,5])
b = tf.constant([1,4,6,4,9])
c = tf.equal(a, b)
print(sess.run(c))

[ True False False  True False]


In [56]:
a = tf.constant([1,22,23,4,50])
b = tf.equal(a, 22)
print(sess.run(b))

[False  True False False False]


In [57]:
a = tf.constant([1,22,23,4,50])
b = tf.constant([1,2,6,4,9])
c = tf.greater(a, b)
print(sess.run(c))

[False  True  True False  True]


In [58]:
a = tf.constant([1,22,23,4,50])
b = tf.constant([1,2,6,4,9])
c = a > b
print(sess.run(c))

[False  True  True False  True]


In [59]:
a = tf.constant([1,22,23,4,50])
b = a > 40
print(sess.run(b))

[False False False False  True]


## * placeholder & Variable 타입

In [61]:
#parameter 타입 꼭!
b = tf.placeholder(tf.float32)
c = tf.placeholder(dtype = tf.float32)
print(b)
print(c)

Tensor("Placeholder_8:0", dtype=float32)
Tensor("Placeholder_9:0", dtype=float32)


In [62]:
a = tf.placeholder(tf.float32)
print(sess.run(a, feed_dict={a:[1.0,2.0,3.0]}))

[1. 2. 3.]


In [63]:
a = tf.placeholder(tf.float32)
print(sess.run(a, feed_dict={a:[1,2,3]}))

[1. 2. 3.]


In [65]:
dic = {}
dic = {"item":"mouse", "qty":5}
dic["item"] = "monitor"
print(dic["item"])
dic = {1.3:"mouse", 4:5}
print(dic[1.3], dic[4])

monitor
mouse 5


In [66]:
a = tf.placeholder(tf.float32)     
dic = {a:[4,5,6]}   
print(a)
print(dic[a])

Tensor("Placeholder_12:0", dtype=float32)
[4, 5, 6]


In [67]:
a = tf.constant([1,2,3,4,5])  
dic = {a:[4,5,6,7,8]}
print(sess.run(a, feed_dict=dic))

[4 5 6 7 8]


In [68]:
#자동 형변환
a = tf.constant([1,2,3,4,5])  
dic = {a:[4,5,6,7.5,8.2]}
print(sess.run(a, feed_dict=dic))

[4 5 6 7 8]


In [69]:
input_data=[1,2,3,4,5]
w = tf.Variable(input_data)
print(w)

<tf.Variable 'Variable_3:0' shape=(5,) dtype=int32_ref>


In [70]:
w = tf.Variable(input_data, dtype=tf.float32)
print(w)

<tf.Variable 'Variable_4:0' shape=(5,) dtype=float32_ref>


In [71]:
init = tf.global_variables_initializer()
print(init)

name: "init_3"
op: "NoOp"
input: "^Variable/Assign"
input: "^Variable_1/Assign"
input: "^Variable_2/Assign"
input: "^Variable_3/Assign"
input: "^Variable_4/Assign"



In [75]:
a = tf.placeholder(tf.float32)
b = tf.Variable([1.0, 3.0, 1.0, 1.0, 2.0], tf.float32)
d1 = b * 2.0
d2 = a * b
init = tf.global_variables_initializer()
sess.run(init)
print(sess.run(d1))

[2. 6. 2. 2. 4.]


In [76]:
print(sess.run(d2,feed_dict={a:[1,2,3,4,5]}) )

[ 1.  6.  3.  4. 10.]


In [77]:
a = tf.placeholder(tf.float32)
b = tf.Variable([1.0, 3.0, 1.0, 1.0, 2.0], tf.float32)
c = a * b
d = a * 2
init = tf.global_variables_initializer()
sess.run(init)
result = sess.run([a, c],feed_dict={a:[1,2,3,4,5]})
print(result[0])
print(result[1])

[1. 2. 3. 4. 5.]
[ 1.  6.  3.  4. 10.]


In [78]:
a_, c_ = sess.run([a, c],feed_dict={a:[1,2,3,4,5]})
print(a_)
print(c_)

[1. 2. 3. 4. 5.]
[ 1.  6.  3.  4. 10.]


In [79]:
a_, _, _ = sess.run([a, c, d],feed_dict={a:[1,2,3,4,5]})
print(a_)

[1. 2. 3. 4. 5.]


In [80]:
a = tf.Variable([1.0,2,3,4,5])
b = a * 10.0
print(sess.run(b, feed_dict={a:[3, 4, 5, 6.0, 9.0]}))

[30. 40. 50. 60. 90.]


In [81]:
print(sess.run(b, feed_dict={a:[3, 4, 5, 6.0, 9.0], b:[1.0, 2, 2, 2, 2]}))

[1. 2. 2. 2. 2.]


In [82]:
input_data=[1,2,3,4,5]
x = tf.placeholder(dtype=tf.float32)
w = tf.Variable([2.0])  
b = tf.constant([1.4])
y = w*x + b     

init = tf.global_variables_initializer()
sess.run(init)
print("y -> ", y)
print("rank(w) ->", sess.run(tf.rank(w)))
print("rank(y) ->", sess.run(tf.rank(y), feed_dict={x:[1,2,3]}))
print("y.op ->", y.op)

y ->  Tensor("add_3:0", dtype=float32)
rank(w) -> 1
rank(y) -> 1
y.op -> name: "add_3"
op: "Add"
input: "mul_12"
input: "Const_55"
attr {
  key: "T"
  value {
    type: DT_FLOAT
  }
}



In [83]:
a = tf.placeholder(tf.float32)
b = tf.Variable([1.0, 1.0, 1.0, 1.0, 2.0], tf.float32)
print(b)
b = a * b   
print(b)

<tf.Variable 'Variable_10:0' shape=(5,) dtype=float32_ref>
Tensor("mul_13:0", dtype=float32)


In [84]:
init = tf.global_variables_initializer()
sess.run(init)
print(sess.run(b,feed_dict={a:[1,2,3,4,5]}))  

[ 1.  2.  3.  4. 10.]


In [87]:
#변수 재정의
w = tf.Variable([1.0, 2.0, 3.0, 4.0, 5.0])
sess.run(tf.global_variables_initializer() )                

for i in range(3):
    w = w * 2
    print(w)
    
print(sess.run(w))

Tensor("mul_18:0", shape=(5,), dtype=float32)
Tensor("mul_19:0", shape=(5,), dtype=float32)
Tensor("mul_20:0", shape=(5,), dtype=float32)
[ 8. 16. 24. 32. 40.]


In [88]:
#변수 재정의 막음
w = tf.Variable([1.0, 2.0, 3.0, 4.0, 5.0])
sess.run(tf.global_variables_initializer() )                

update = tf.assign(w, w*2)   

for i in range(3):
    sess.run(update)     
    print(update)

print(sess.run(w))  

Tensor("Assign_1:0", shape=(5,), dtype=float32_ref)
Tensor("Assign_1:0", shape=(5,), dtype=float32_ref)
Tensor("Assign_1:0", shape=(5,), dtype=float32_ref)
[ 8. 16. 24. 32. 40.]


In [89]:
input_data=[1,2,3,4,5]
x = tf.placeholder(dtype=tf.float32)
w = tf.Variable([2.0])  
b = tf.constant([1.4])
y = w*x + b     

init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init)

out1 = sess.run(y , feed_dict={x:[1,2,3]})   # [3.4 5.4 7.4]
out2 = sess.run(y , feed_dict={x:[-1.0,-2.0]})  # [-0.6 -2.6]

print(out1)
print(out2)

[3.4 5.4 7.4]
[-0.6 -2.6]
