### 1. 행렬 초기화 

In [3]:
import tensorflow as tf
import numpy as np
sess = tf.Session()

In [4]:
a = tf.zeros([2,10])
b = tf.ones([2,10], tf.int32)
c = tf.eye(3)
print(sess.run(a))
print(sess.run(b))
print(sess.run(c))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
a = tf.constant([1,2,3,4,5])
b = tf.cast(a, dtype = tf.float32)
print(sess.run(a))
print(sess.run(b))

[1 2 3 4 5]
[1. 2. 3. 4. 5.]


In [6]:
a = tf.constant([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b = tf.slice(a, [1,0], [2,2])
print(sess.run(a))
print(sess.run(b))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[4 5]
 [7 8]]


In [7]:
a = tf.constant([1,2,3,4])
b = tf.constant([5,6,7,8,9], name="b")
print(a)
print(b)

Tensor("Const_2:0", shape=(4,), dtype=int32)
Tensor("b:0", shape=(5,), dtype=int32)


### 행렬곱

In [8]:
x = tf.constant([[1,2],[4,5]])
y = tf.constant([[1,2,3],[4,5,6]])
z = tf.matmul(x, y)
print(sess.run(z))

[[ 9 12 15]
 [24 33 42]]


In [10]:
a = tf.constant([[1.0,2],[7,8]])
b = tf.linalg.inv(a)
print(sess.run(a))
print(sess.run(b))

[[1. 2.]
 [7. 8.]]
[[-1.3333335   0.33333337]
 [ 1.1666667  -0.16666669]]


### 브로드캐스팅

In [11]:
a = tf.constant([[1,2,3],[4,5,6]])
b = a+4
print(sess.run(a))
print(sess.run(b))

[[1 2 3]
 [4 5 6]]
[[ 5  6  7]
 [ 8  9 10]]


###  Reduce함수 : 대표값으로 차원을 줄여줌

In [12]:
a = tf.constant([1.0,2,3,4,5,6,7,8,9,10])
print(sess.run(tf.reduce_sum(a)))
print(sess.run(tf.reduce_mean(a)))
print(sess.run(tf.reduce_max(a)))
print(sess.run(tf.reduce_min(a)))


55.0
5.5
10.0
1.0
